// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://teqjzuaezrddrtfhqpxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlcWp6dWFlenJkZHJ0ZmhxcHhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MTQzNTgsImV4cCI6MjA3MjM5MDM1OH0.sV_PS7w8uNaTwUQgxzUOL18eRob2CvQTtoPvwx6ijxw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});